/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jw_usejni_JniSample */

#ifndef _Included_jw_usejni_JniSample
#define _Included_jw_usejni_JniSample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jw_usejni_JniSample
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jw_usejni_JniSample_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
